export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const FETCH_ALL_CONTACTS = 'FETCH_ALL_CONTACTS';
export const NEXT_SIGN_UP_STEP = 'NEXT_SIGN_UP_STEP';
export const PREV_SIGN_UP_STEP = 'PREV_SIGN_UP_STEP';
export const RESET_SIGN_UP = 'RESET_SIGN_UP';
export const UPDATE_SIGN_UP_DATA = 'UPDATE_SIGN_UP_DATA';

export const CHANGE_LOADING_USER_PROFILE = 'CHANGE_LOADING_USER_PROFILE';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
